# Generated by Django 3.2.4 on 2021-07-15 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chef_chantier', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='missions',
            new_name='mission',
        ),
    ]
