# Generated by Django 3.2.6 on 2021-08-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_chantier', '0003_mission_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='date_debut',
            field=models.DateField(),
        ),
    ]
