# Generated by Django 3.2.6 on 2021-08-21 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chef_chantier', '0004_alter_mission_date_debut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='User',
        ),
        migrations.AddField(
            model_name='mission',
            name='chef_chantier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chef_chantier.chef_chantier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mission',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employes.user'),
            preserve_default=False,
        ),
    ]
