# Generated by Django 3.2.6 on 2021-08-21 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chef_chantier', '0005_auto_20210821_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='chef_chantier',
        ),
    ]
