# Generated by Django 3.2.6 on 2021-08-21 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chef_chantier', '0006_remove_mission_chef_chantier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mission',
            old_name='user',
            new_name='User',
        ),
    ]
