# Generated by Django 3.2.6 on 2021-08-07 14:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0004_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointage',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
