# Generated by Django 3.2.6 on 2021-08-07 14:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0005_pointage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaire',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
