# Generated by Django 3.2.6 on 2021-08-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0006_salaire_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='user',
            name='prenom',
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
