# Generated by Django 3.2.6 on 2021-08-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0007_auto_20210808_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(),
        ),
    ]
