# Generated by Django 3.2.6 on 2021-08-09 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0008_alter_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='employes.user')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pointage',
            name='user',
            field=models.ManyToManyField(to='employes.UserProfile'),
        ),
        migrations.AlterField(
            model_name='salaire',
            name='user',
            field=models.ManyToManyField(to='employes.UserProfile'),
        ),
    ]
