# Generated by Django 3.2.6 on 2021-08-21 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0009_auto_20210809_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointage',
            name='user',
        ),
        migrations.AddField(
            model_name='pointage',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employes.user'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='salaire',
            name='user',
        ),
        migrations.AddField(
            model_name='salaire',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employes.user'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
